<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE root[<!ELEMENT Class ANY> <!ATTLIST Class ClassName ID #REQUIRED>]>
<root>
  <Class ClassName="XDummyOrgFile" Describle="虛擬組織附件" IAuditObject="False" DataEntity="True" INamedObject="False" IFlagObject="True" IOwnerObject="True" ICodeObject="False" IDataModifyObject="True" Collection="True" IsCase="False">
    <Parameter Name="XDummyOrgFileId" Type="Guid" Describe="附件ID" ReferenceProperty="" />
    <Parameter Name="DummyOrgId" Type="Guid" Describe="虛擬組織Id" ReferenceProperty="DummyOrg" />
    <Parameter Name="XFileCreateDate" Type="DateTime" Describe="創建日期" ReferenceProperty="" />
    <Parameter Name="XDescribe1" Type="string" Describe="議程1" ReferenceProperty="" />
    <Parameter Name="XDescribe2" Type="string" Describe="議程2" ReferenceProperty="" />
    <Parameter Name="XDescribe3" Type="string" Describe="議程3" ReferenceProperty="" />
    <Parameter Name="XDescribe4" Type="string" Describe="議程4" ReferenceProperty="" />
    <Parameter Name="XDescribe5" Type="string" Describe="議程5" ReferenceProperty="" />
    <Parameter Name="XDescribe6" Type="string" Describe="議程6" ReferenceProperty="" />
    <Parameter Name="XFileRemark" Type="Ntext" Describe="備註" ReferenceProperty="" />
    <Parameter Name="CreateDate" Type="DateTime" Describe="建立日期" ReferenceProperty="" />
    <Parameter Name="LastModifiedDate" Type="DateTime" Describe="最後一次編輯日期" ReferenceProperty="" />
    <Parameter Name="CreateBy" Type="Guid" Describe="建立 用戶ID" ReferenceProperty="User" />
    <Parameter Name="LastModifiedBy" Type="Guid" Describe="最後一次編輯 用戶ID" ReferenceProperty="User" />
    <Parameter Name="Flag" Type="Bool" Describe="是否有效" ReferenceProperty="" />
    <Parameter Name="AssignReason" Type="string" Describe="分配原因" ReferenceProperty="" />
    <Parameter Name="OwnerId" Type="string" Describe="所有者ID" ReferenceProperty="User" />
  </Class>
  <Class ClassName="XDummyOrgFileDetail" Describle="虛擬組織附件明細" IAuditObject="False" DataEntity="True" INamedObject="False" IFlagObject="True" IOwnerObject="True" ICodeObject="False" IDataModifyObject="True" Collection="False" IsCase="False">
    <Parameter Name="XDummyOrgFileDetailId" Type="Guid" Describe="附件明細ID" ReferenceProperty="" />
    <Parameter Name="XDummyOrgFileId" Type="Guid" Describe="附件ID" ReferenceProperty="XDummyOrgFile" />
    <Parameter Name="XFile" Type="string" Describe="附件" ReferenceProperty="" />
    <Parameter Name="XFileName" Type="string" Describe="附件名稱" ReferenceProperty="" />
    <Parameter Name="XFileType" Type="string" Describe="附件類型" ReferenceProperty="" />
    <Parameter Name="XFileSize" Type="Int" Describe="附件大小" ReferenceProperty="" />
    <Parameter Name="XFileRemark" Type="Ntext" Describe="附件備註" ReferenceProperty="" />
    <Parameter Name="AssignReason" Type="string" Describe="分配原因" ReferenceProperty="" />
    <Parameter Name="OwnerId" Type="string" Describe="所有者ID" ReferenceProperty="User" />
    <Parameter Name="CreateDate" Type="DateTime" Describe="建立日期" ReferenceProperty="" />
    <Parameter Name="LastModifiedDate" Type="DateTime" Describe="最後一次編輯日期" ReferenceProperty="" />
    <Parameter Name="CreateBy" Type="Guid" Describe="建立 用戶ID" ReferenceProperty="User" />
    <Parameter Name="LastModifiedBy" Type="Guid" Describe="最後一次編輯 用戶ID" ReferenceProperty="User" />
    <Parameter Name="Flag" Type="Bool" Describe="是否有效" ReferenceProperty="" />
  </Class>
  <Class ClassName="XEmpTempHour" Describle="臨時人員工時管理" IAuditObject="False" DataEntity="True" INamedObject="False" IFlagObject="True" IOwnerObject="True" ICodeObject="False" IDataModifyObject="True" Collection="False" IsCase="False">
    <Parameter Name="XEmpTempHourId" Type="Guid" Describe="臨時人員工時管理Id" ReferenceProperty="" />
    <Parameter Name="EmployeeId" Type="Guid" Describe="臨時人員" ReferenceProperty="Employee" />
    <Parameter Name="DepartmentId" Type="Guid" Describe="廳別" ReferenceProperty="Department" />
    <Parameter Name="Date" Type="DateTime" Describe="日期" ReferenceProperty="" />
    <Parameter Name="Hours" Type="decimal" Describe="工時" ReferenceProperty="" />
    <Parameter Name="Base" Type="decimal" Describe="倍率" ReferenceProperty="" />
    <Parameter Name="CreateDate" Type="DateTime" Describe="建立日期" ReferenceProperty="" />
    <Parameter Name="LastModifiedDate" Type="DateTime" Describe="最後一次編輯日期" ReferenceProperty="" />
    <Parameter Name="CreateBy" Type="Guid" Describe="建立 用戶ID" ReferenceProperty="User" />
    <Parameter Name="LastModifiedBy" Type="Guid" Describe="最後一次編輯 用戶ID" ReferenceProperty="User" />
    <Parameter Name="Flag" Type="Bool" Describe="是否有效" ReferenceProperty="" />
    <Parameter Name="AssignReason" Type="string" Describe="分配原因" ReferenceProperty="" />
    <Parameter Name="OwnerId" Type="string" Describe="所有者ID" ReferenceProperty="User" />
    <Parameter Name="TempLate" Type="string" Describe="測試1" ReferenceProperty="" />
  </Class>
  <Class ClassName="XSISetting" Describle="系統整合設定" IAuditObject="False" DataEntity="True" INamedObject="False" IFlagObject="True" IOwnerObject="True" ICodeObject="False" IDataModifyObject="True" Collection="False" IsCase="False">
    <Parameter Name="XSISettingID" Type="Guid" Describe="SI設定ID" ReferenceProperty="" Order="" UIOrder="" Necessary="False" />
    <Parameter Name="XSystemName" Type="string" Describe="整合系統" ReferenceProperty="" Order="1" UIOrder="" Necessary="False" />
    <Parameter Name="XFileCode" Type="string" Describe="資料編號" ReferenceProperty="" Order="2" UIOrder="" Necessary="True" />
    <Parameter Name="XFileName" Type="string" Describe="資料名稱" ReferenceProperty="" Order="3" UIOrder="" Necessary="True" />
    <Parameter Name="XFileType" Type="string" Describe="資料格式" ReferenceProperty="" Order="4" UIOrder="" Necessary="True" />
    <Parameter Name="XConnectType" Type="string" Describe="連結方式" ReferenceProperty="" Order="5" UIOrder="" Necessary="False" />
    <Parameter Name="XConnectRoute" Type="string" Describe="連線路徑" ReferenceProperty="" Order="6" UIOrder="" Necessary="False" />
    <Parameter Name="XPort" Type="string" Describe="Port" ReferenceProperty="" Order="7" UIOrder="" Necessary="False" />
    <Parameter Name="XDocName" Type="string" Describe="資料夾名稱" ReferenceProperty="" Order="8" UIOrder="" Necessary="False" />
    <Parameter Name="XUserID" Type="string" Describe="登入帳號" ReferenceProperty="" Order="" UIOrder="" Necessary="False" />
    <Parameter Name="XPassword" Type="string" Describe="登入密碼" ReferenceProperty="" Order="" UIOrder="" Necessary="False" />
    <Parameter Name="XTriggerStart" Type="string" Describe="觸發時間" ReferenceProperty="" Order="" UIOrder="" Necessary="False" />
    <Parameter Name="XLoopHours" Type="string" Describe="循環時數" ReferenceProperty="" Order="" UIOrder="" Necessary="False" />
    <Parameter Name="XRemark" Type="Ntext" Describe="備註" ReferenceProperty="" Order="" UIOrder="" Necessary="False" />
    <Parameter Name="IsActive" Type="Bool" Describe="是否啟用" ReferenceProperty="" Order="" UIOrder="" Necessary="False" />
    <Parameter Name="Flag" Type="Bool" Describe="是否有效" ReferenceProperty="" Order="" UIOrder="" Necessary="False" />
    <Parameter Name="AssignReason" Type="string" Describe="分配原因" ReferenceProperty="" Order="" UIOrder="" Necessary="False" />
    <Parameter Name="OwnerId" Type="string" Describe="所有者ID" ReferenceProperty="User" Order="" UIOrder="" Necessary="False" />
    <Parameter Name="CreateDate" Type="DateTime" Describe="建立日期" ReferenceProperty="" Order="" UIOrder="" Necessary="False" />
    <Parameter Name="LastModifiedDate" Type="DateTime" Describe="最後一次編輯日期" ReferenceProperty="" Order="" UIOrder="" Necessary="False" />
    <Parameter Name="CreateBy" Type="Guid" Describe="建立 用戶ID" ReferenceProperty="User" Order="" UIOrder="" Necessary="False" />
    <Parameter Name="LastModifiedBy" Type="Guid" Describe="最後一次編輯 用戶ID" ReferenceProperty="User" Order="" UIOrder="" Necessary="False" />
  </Class>
</root>